const fs=require('fs'),vm=require('vm'),assert=require('assert');
const code=fs.readFileSync(process.argv[2],'utf8');
const nodes=new Map(),saved=new Map(),blobs=new Map(),downloads=[];
const ctx=new Proxy({getImageData:()=>({data:[0,0,0,255]})},{get:(o,k)=>o[k]||(()=>{})});
class El{constructor(){this.value='';this.options=[];this.handlers={};this.style={};this.checked=false;this.children=[];}append(...xs){this.children.push(...xs);this.options.push(...xs);if(!this.value&&xs[0]?.value)this.value=xs[0].value;}replaceChildren(){this.children=[];this.options=[];}addEventListener(k,fn){this.handlers[k]=fn}getBoundingClientRect(){return{width:800,height:700,left:0,top:0}}getContext(){return ctx}click(){if(this.download)downloads.push({name:this.download,blob:blobs.get(this.href)});else this.onclick?.()}setPointerCapture(){}toBlob(fn){fn(new Blob(['png-test']))}}
function el(id){if(!nodes.has(id))nodes.set(id,new El());return nodes.get(id)}
el('assetType').value='head';el('background').value='paper';el('showAnchors').checked=true;
const sandbox={console,Blob,setTimeout:fn=>fn(),Image:class{constructor(){this.complete=true;this.naturalWidth=200;this.naturalHeight=200;}set src(v){this._src=v}get src(){return this._src}},document:{getElementById:el,createElement:()=>new El()},localStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)},window:{devicePixelRatio:1,addEventListener(){},open(){}},crypto:{randomUUID:require('crypto').randomUUID},requestAnimationFrame(){},URL:{createObjectURL:b=>{const id='blob:'+Math.random();blobs.set(id,b);return id},revokeObjectURL(){}},confirm:()=>true};
vm.createContext(sandbox);vm.runInContext(code,sandbox);const run=s=>vm.runInContext(s,sandbox);let count=0;function test(name,fn){fn();count++;console.log('PASS '+name)}
test('示例包含五类八件部件',()=>{assert.equal(run('state.parts.length'),8);assert.equal(run('new Set(state.parts.map(p=>p.type)).size'),5)});
test('镜像后部件锚点精确连接身体接口',()=>{assert(run('state.parts.filter(p=>p.type!=="body").every(p=>{const a=point(transform(p),...p.anchor),b=point(rootTransform(body()),...body().ports[p.mount]);return Math.hypot(a.x-b.x,a.y-b.y)<1e-8})'))});
test('身体移动带动所有部件',()=>{assert.equal(run('(()=>{const p=state.parts.find(p=>p.type==="head"),before=transform(p).x;body().x+=70;return transform(p).x-before})()'),70)});
test('修改身体接口带动头部',()=>{assert.equal(run('(()=>{const p=state.parts.find(p=>p.type==="head"),before=transform(p).y;body().ports.neck[1]+=.1;return Math.round(transform(p).y-before)})()'),20)});
test('整体文件结构可往返',()=>{assert.equal(run('validateProject(JSON.parse(JSON.stringify(state))).parts.length'),8)});
test('层级控制绘制顺序',()=>{assert.equal(run('sorted()[0].type'),'wing');assert.equal(run('sorted().at(-1).type'),'head')});
test('无效导入被拒绝且组合保留',()=>{assert.throws(()=>run('validateProject({...clone(state),version:99})'));assert.throws(()=>run('validAsset({type:"head",name:"bad",src:"https://external.invalid/x.png",ratio:1})'));assert.equal(run('state.parts.length'),8)});
test('组件导出包含内嵌图片和连接参数',()=>{run('selected=state.parts.find(p=>p.type==="head").id;$("savePart").onclick()');assert.equal(downloads.length,1);assert(downloads[0].name.endsWith('.component.json'))});
test('整体导出记录操作并可撤销',()=>{run('$("saveProject").onclick()');assert.equal(downloads.length,2);run('selected=state.parts.find(p=>p.type==="head").id;$("duplicate").onclick()');assert.equal(run('state.parts.length'),9);run('$("undo").onclick()');assert.equal(run('state.parts.length'),8);run('$("redo").onclick()');assert.equal(run('state.parts.length'),9)});
(async()=>{const one=JSON.parse(await downloads[0].blob.text()),all=JSON.parse(await downloads[1].blob.text());assert.equal(one.schema,'monster-component');assert(one.asset.src.startsWith('data:image/'));assert.equal(one.part.anchor.length,2);assert.equal(all.schema,'monster-assembly');assert.equal(all.parts.length,8);console.log('PASS 实际导出 Blob 内容与往返格式');sandbox.fixture={size:200,text:async()=>JSON.stringify(one)};run('$("importPart").onclick();$("fileInput").files=[fixture]');await run('$("fileInput").onchange()');assert.equal(run('state.parts.length'),10);console.log('PASS 组件导入回调恢复参数并添加新部件');sandbox.fixture={size:200,name:'test.monster.json',text:async()=>JSON.stringify(all)};run('$("loadProject").onclick();$("fileInput").files=[fixture]');await run('$("fileInput").onchange()');assert.equal(run('state.parts.length'),8);assert.equal(run('validateProject(state).parts.length'),8);console.log('PASS 整体导入回调恢复组合与素材');console.log('TOTAL '+(count+3)+' checks passed');})().catch(e=>{console.error(e);process.exitCode=1});
