globalThis.EventSeed = {
  "schema_version": 1,
  "name": "超级怪物计划 · 叙事事件",
  "tables": {
    "events": [
      {
        "id": "QST_MAIN_001_001",
        "name": "火速任命",
        "category": "主线",
        "summary": "王国特使任命召唤师重启计划",
        "trigger": "新游戏",
        "entry": "",
        "condition_group": "",
        "accept": "自动",
        "initial_stage": "",
        "start_node": "",
        "repeat": "一次性",
        "time_rule": "暂停探索",
        "result_group": "",
        "status": "草稿"
      },
      {
        "id": "QST_MAIN_001_002",
        "name": "旅途准备",
        "category": "教学",
        "summary": "学习召唤并完成首次召唤",
        "trigger": "前置完成",
        "entry": "",
        "condition_group": "",
        "accept": "自动",
        "initial_stage": "",
        "start_node": "",
        "repeat": "一次性",
        "time_rule": "暂停探索",
        "result_group": "",
        "status": "草稿"
      },
      {
        "id": "QST_SIDE_001_001",
        "name": "图书馆开门日",
        "category": "支线",
        "summary": "在福斯特镇从罗瓦处收回手记",
        "trigger": "交互",
        "entry": "",
        "condition_group": "",
        "accept": "确认",
        "initial_stage": "",
        "start_node": "",
        "repeat": "一次性",
        "time_rule": "暂停探索",
        "result_group": "",
        "status": "草稿"
      },
      {
        "id": "QST_SIDE_002_001",
        "name": "防卫预算",
        "category": "支线",
        "summary": "完成三场标记战斗后回城交付",
        "trigger": "交互",
        "entry": "",
        "condition_group": "",
        "accept": "确认",
        "initial_stage": "",
        "start_node": "",
        "repeat": "一次性",
        "time_rule": "暂停探索",
        "result_group": "",
        "status": "草稿"
      },
      {
        "id": "QST_SIDE_004_001",
        "name": "不老贤者里斯巴巴",
        "category": "支线",
        "summary": "寻找草原北部遗迹与贤者手记",
        "trigger": "交互",
        "entry": "",
        "condition_group": "",
        "accept": "确认",
        "initial_stage": "",
        "start_node": "",
        "repeat": "一次性",
        "time_rule": "暂停探索",
        "result_group": "",
        "status": "草稿"
      },
      {
        "id": "QST_SIDE_003_001",
        "name": "血祭日",
        "category": "支线",
        "summary": "在祭坛格完成三类献祭，获得奇物并使本格永久血雨",
        "trigger": "交互",
        "entry": "interact_blood_altar",
        "condition_group": "CG_AT_ALTAR",
        "accept": "自动",
        "initial_stage": "S_BLOOD_READ",
        "start_node": "D_BLOOD_001",
        "repeat": "一次性",
        "time_rule": "暂停探索",
        "result_group": "R_BLOOD_COMPLETE",
        "status": "待绑定"
      },
      {
        "id": "QST_SIDE_005_001",
        "name": "愿望的格式",
        "category": "支线",
        "summary": "从福斯特镇获得林中小屋线索，再寻找许愿树",
        "trigger": "交互",
        "entry": "",
        "condition_group": "",
        "accept": "确认",
        "initial_stage": "",
        "start_node": "",
        "repeat": "一次性",
        "time_rule": "暂停探索",
        "result_group": "",
        "status": "草稿"
      }
    ],
    "goals": [
      {
        "id": "OBJ_BLOOD_READ",
        "event_id": "QST_SIDE_003_001",
        "stage_id": "S_BLOOD_READ",
        "stage_order": 1,
        "description": "阅读碑文并查看三条要求",
        "type": "交互完成",
        "target": "interact_blood_altar",
        "quantity": 1,
        "monster_condition": "",
        "location_condition": "CG_AT_ALTAR",
        "completion": "ALL",
        "next_stage": "S_BLOOD_OFFER",
        "result_group": "",
        "submit_rule": "完整展示到献祭面板后登记阅读",
        "submit_condition": ""
      },
      {
        "id": "OBJ_BLOOD_FAST",
        "event_id": "QST_SIDE_003_001",
        "stage_id": "S_BLOOD_OFFER",
        "stage_order": 2,
        "description": "献祭飞行或快速移动怪物3个",
        "type": "献祭",
        "target": "candidate_monster",
        "quantity": 3,
        "monster_condition": "CG_MONSTER_FAST",
        "location_condition": "CG_AT_ALTAR",
        "completion": "ALL",
        "next_stage": "",
        "result_group": "R_BLOOD_COMPLETE",
        "submit_rule": "分批；每只计入一项；建议",
        "submit_condition": "CG_CAN_OFFER"
      },
      {
        "id": "OBJ_BLOOD_FUR",
        "event_id": "QST_SIDE_003_001",
        "stage_id": "S_BLOOD_OFFER",
        "stage_order": 2,
        "description": "献祭带皮毛怪物7个",
        "type": "献祭",
        "target": "candidate_monster",
        "quantity": 7,
        "monster_condition": "CG_MONSTER_FUR",
        "location_condition": "CG_AT_ALTAR",
        "completion": "ALL",
        "next_stage": "",
        "result_group": "R_BLOOD_COMPLETE",
        "submit_rule": "分批；每只计入一项；建议",
        "submit_condition": "CG_CAN_OFFER"
      },
      {
        "id": "OBJ_BLOOD_LIMBLESS",
        "event_id": "QST_SIDE_003_001",
        "stage_id": "S_BLOOD_OFFER",
        "stage_order": 2,
        "description": "献祭无手且无脚组件怪物1个",
        "type": "献祭",
        "target": "candidate_monster",
        "quantity": 1,
        "monster_condition": "CG_MONSTER_LIMBLESS",
        "location_condition": "CG_AT_ALTAR",
        "completion": "ALL",
        "next_stage": "",
        "result_group": "R_BLOOD_COMPLETE",
        "submit_rule": "分批；每只计入一项；建议",
        "submit_condition": "CG_CAN_OFFER"
      }
    ],
    "nodes": [
      {
        "id": "D_BLOOD_001",
        "event_id": "QST_SIDE_003_001",
        "stage_id": "S_BLOOD_READ",
        "type": "对话",
        "speaker": "speaker_inscription",
        "text": "那头兽只为猩红而生，漫步于无名之野。",
        "portrait": "",
        "interaction": "",
        "result_group": "",
        "next_node": "D_BLOOD_002",
        "note": "来源：事件.xlsx D45"
      },
      {
        "id": "D_BLOOD_002",
        "event_id": "QST_SIDE_003_001",
        "stage_id": "S_BLOOD_READ",
        "type": "对话",
        "speaker": "speaker_inscription",
        "text": "为其献上血的祭礼，其必将回以血的报答。",
        "portrait": "",
        "interaction": "",
        "result_group": "",
        "next_node": "D_BLOOD_003",
        "note": "来源：事件.xlsx D46"
      },
      {
        "id": "D_BLOOD_003",
        "event_id": "QST_SIDE_003_001",
        "stage_id": "S_BLOOD_READ",
        "type": "对话",
        "speaker": "speaker_inscription",
        "text": "红日升起，红雨落下，此为血祭之日。",
        "portrait": "",
        "interaction": "",
        "result_group": "",
        "next_node": "D_BLOOD_004",
        "note": "来源：事件.xlsx D47"
      },
      {
        "id": "D_BLOOD_004",
        "event_id": "QST_SIDE_003_001",
        "stage_id": "S_BLOOD_READ",
        "type": "笔记",
        "speaker": "speaker_altar",
        "text": "飞行或者快速移动的怪物，献祭3个。",
        "portrait": "",
        "interaction": "",
        "result_group": "",
        "next_node": "D_BLOOD_005",
        "note": "2026-10-06确认；明确条件说明"
      },
      {
        "id": "D_BLOOD_005",
        "event_id": "QST_SIDE_003_001",
        "stage_id": "S_BLOOD_READ",
        "type": "笔记",
        "speaker": "speaker_altar",
        "text": "带皮毛的怪物，献祭7个。",
        "portrait": "",
        "interaction": "",
        "result_group": "",
        "next_node": "D_BLOOD_006",
        "note": "2026-10-06确认"
      },
      {
        "id": "D_BLOOD_006",
        "event_id": "QST_SIDE_003_001",
        "stage_id": "S_BLOOD_READ",
        "type": "笔记",
        "speaker": "speaker_altar",
        "text": "没有手脚组件的怪物，献祭1个。所有献祭必须在祭坛所在格子完成。",
        "portrait": "",
        "interaction": "",
        "result_group": "",
        "next_node": "N_BLOOD_PANEL",
        "note": "2026-10-06确认"
      },
      {
        "id": "N_BLOOD_PANEL",
        "event_id": "QST_SIDE_003_001",
        "stage_id": "",
        "type": "交互",
        "speaker": "",
        "text": "查看献祭要求与进度",
        "portrait": "",
        "interaction": "sacrifice_panel",
        "result_group": "",
        "next_node": "END",
        "note": "跨阶段共用面板节点；初次打开登记阅读，提交另受CG_CAN_OFFER限制"
      }
    ],
    "choices": [],
    "conditions": [
      {
        "id": "C_AT_ALTAR",
        "group_id": "CG_AT_ALTAR",
        "relation": "ALL",
        "object": "map_context",
        "field": "current_cell_id",
        "operator": "EQ",
        "value": "cell_blood_altar",
        "value_type": "ID",
        "scope": "当前格",
        "note": "必须与祭坛所在实际格子相同",
        "event_id": "QST_SIDE_003_001"
      },
      {
        "id": "C_FLYING",
        "group_id": "CG_MONSTER_FAST",
        "relation": "ANY",
        "object": "candidate_monster",
        "field": "has_flying",
        "operator": "EQ",
        "value": true,
        "value_type": "BOOL",
        "scope": "候选怪物",
        "note": "飞行能力；正式字段需怪物系统绑定",
        "event_id": "QST_SIDE_003_001"
      },
      {
        "id": "C_FAST",
        "group_id": "CG_MONSTER_FAST",
        "relation": "ANY",
        "object": "candidate_monster",
        "field": "has_fast_movement",
        "operator": "EQ",
        "value": true,
        "value_type": "BOOL",
        "scope": "候选怪物",
        "note": "快速移动能力；不擅自设速度阈值",
        "event_id": "QST_SIDE_003_001"
      },
      {
        "id": "C_FUR",
        "group_id": "CG_MONSTER_FUR",
        "relation": "ALL",
        "object": "candidate_monster",
        "field": "has_fur",
        "operator": "EQ",
        "value": true,
        "value_type": "BOOL",
        "scope": "候选怪物",
        "note": "皮毛正式特征，不是外观判断",
        "event_id": "QST_SIDE_003_001"
      },
      {
        "id": "C_NO_HAND",
        "group_id": "CG_MONSTER_LIMBLESS",
        "relation": "ALL",
        "object": "candidate_monster",
        "field": "hand_component_count",
        "operator": "EQ",
        "value": 0,
        "value_type": "NUMBER",
        "scope": "候选怪物",
        "note": "手组件数量为0",
        "event_id": "QST_SIDE_003_001"
      },
      {
        "id": "C_NO_FOOT",
        "group_id": "CG_MONSTER_LIMBLESS",
        "relation": "ALL",
        "object": "candidate_monster",
        "field": "foot_component_count",
        "operator": "EQ",
        "value": 0,
        "value_type": "NUMBER",
        "scope": "候选怪物",
        "note": "脚组件数量为0，触须不自动算手脚",
        "event_id": "QST_SIDE_003_001"
      },
      {
        "id": "C_ACTIVE",
        "group_id": "CG_CAN_OFFER",
        "relation": "ALL",
        "object": "event_state",
        "field": "QST_SIDE_003_001.status",
        "operator": "EQ",
        "value": "进行中",
        "value_type": "TEXT",
        "scope": "本事件",
        "note": "提交面板先检查事件状态",
        "event_id": "QST_SIDE_003_001"
      },
      {
        "id": "C_STAGE",
        "group_id": "CG_CAN_OFFER",
        "relation": "ALL",
        "object": "event_state",
        "field": "QST_SIDE_003_001.stage",
        "operator": "EQ",
        "value": "S_BLOOD_OFFER",
        "value_type": "ID",
        "scope": "本事件",
        "note": "只能在献祭阶段提交",
        "event_id": "QST_SIDE_003_001"
      },
      {
        "id": "C_OFFER_CELL",
        "group_id": "CG_CAN_OFFER",
        "relation": "ALL",
        "object": "map_context",
        "field": "current_cell_id",
        "operator": "EQ",
        "value": "cell_blood_altar",
        "value_type": "ID",
        "scope": "当前格",
        "note": "每次确认重新检查地点",
        "event_id": "QST_SIDE_003_001"
      },
      {
        "id": "C_COUNT_FAST",
        "group_id": "CG_BLOOD_DONE",
        "relation": "ALL",
        "object": "objective_state",
        "field": "OBJ_BLOOD_FAST.count",
        "operator": "GTE",
        "value": 3,
        "value_type": "NUMBER",
        "scope": "本事件",
        "note": "已提交数量达到3",
        "event_id": "QST_SIDE_003_001"
      },
      {
        "id": "C_COUNT_FUR",
        "group_id": "CG_BLOOD_DONE",
        "relation": "ALL",
        "object": "objective_state",
        "field": "OBJ_BLOOD_FUR.count",
        "operator": "GTE",
        "value": 7,
        "value_type": "NUMBER",
        "scope": "本事件",
        "note": "已提交数量达到7",
        "event_id": "QST_SIDE_003_001"
      },
      {
        "id": "C_COUNT_LIMBLESS",
        "group_id": "CG_BLOOD_DONE",
        "relation": "ALL",
        "object": "objective_state",
        "field": "OBJ_BLOOD_LIMBLESS.count",
        "operator": "GTE",
        "value": 1,
        "value_type": "NUMBER",
        "scope": "本事件",
        "note": "已提交数量达到1",
        "event_id": "QST_SIDE_003_001"
      }
    ],
    "actions": [
      {
        "id": "A_BLOOD_RELIC",
        "group_id": "R_BLOOD_COMPLETE",
        "type": "给予奇物",
        "target": "relic_blood_crystal",
        "value": 1,
        "value_type": "NUMBER",
        "timing": "阶段完成",
        "condition_group": "CG_BLOOD_DONE",
        "scope": "玩家",
        "duration": "永久",
        "once_key": "blood.reward_once",
        "note": "原表浊血晶；正式名称/ID待统一",
        "event_id": "QST_SIDE_003_001"
      },
      {
        "id": "A_BLOOD_RAIN",
        "group_id": "R_BLOOD_COMPLETE",
        "type": "设置天气",
        "target": "weather_blood_rain",
        "value": true,
        "value_type": "BOOL",
        "timing": "阶段完成",
        "condition_group": "CG_BLOOD_DONE",
        "scope": "cell_blood_altar",
        "duration": "永久",
        "once_key": "blood.weather_once",
        "note": "只改这一格，绝不扩展为沙漠地区",
        "event_id": "QST_SIDE_003_001"
      },
      {
        "id": "A_BLOOD_DONE",
        "group_id": "R_BLOOD_COMPLETE",
        "type": "完成事件",
        "target": "QST_SIDE_003_001",
        "value": "已完成",
        "value_type": "TEXT",
        "timing": "阶段完成",
        "condition_group": "CG_BLOOD_DONE",
        "scope": "本事件",
        "duration": "永久",
        "once_key": "blood.complete_once",
        "note": "与奖励/天气同一结果组提交",
        "event_id": "QST_SIDE_003_001"
      }
    ],
    "maps": [
      {
        "id": "MAP_BLOOD_ALTAR",
        "event_id": "QST_SIDE_003_001",
        "region_id": "region_desert_edge",
        "cell_id": "cell_blood_altar",
        "location_id": "location_blood_altar",
        "interaction_id": "interact_blood_altar",
        "name": "血祭祭坛",
        "first_node": "D_BLOOD_001",
        "active_node": "N_BLOOD_PANEL",
        "completed_text": "祭礼已经完成。此格仍下着血雨。",
        "change_scope": "cell_blood_altar",
        "status": "待绑定"
      }
    ]
  }
};

