extends SceneTree
const WINDOW := preload("res://ui/event_window.tscn")
var requests := 0
var closes := 0
var request_id := ""

func _initialize() -> void:
	call_deferred("_run")

func _run() -> void:
	var window = WINDOW.instantiate()
	root.add_child(window)
	await process_frame
	var data: Dictionary = JSON.parse_string(FileAccess.get_file_as_string("res://data/library_demo.json"))
	window.reward_requested.connect(func(id, _rewards):
		requests += 1
		request_id = id)
	window.event_closed.connect(func(_id): closes += 1)
	assert(window.open_event({}, "test") == ERR_INVALID_DATA)
	assert(window.open_event(data, "test") == OK)
	assert(window.open_event(data, "test") == ERR_BUSY)
	assert(window.transcript.size() == 1)
	window.close_event()
	assert(window.is_open(), "Cannot dismiss before ending")
	window.advance()
	window.advance()
	window.advance()
	assert(window.get_state() == "choice")
	assert(window.transcript.size() == 3)
	window.advance()
	window.select_choice("missing")
	assert(window.get_state() == "choice")
	window.select_choice("take")
	assert(window.transcript.size() == 5)
	assert(window.transcript[3].speaker == "召唤师")
	window.select_choice("ask")
	assert(window.transcript.size() == 5, "Cannot select twice")
	window.advance()
	window.advance()
	assert(window.get_state() == "reward_pending")
	assert(requests == 1)
	window.advance()
	assert(requests == 1)
	assert(not window.acknowledge_reward("wrong", true))
	assert(not window.acknowledge_reward(request_id, false, "失败"))
	assert(window.get_state() == "reward_pending")
	assert(window.acknowledge_reward(request_id, true))
	assert(not window.acknowledge_reward(request_id, true))
	assert(window.transcript.size() == 7)
	assert(window.get_state() == "end")
	await process_frame
	var count: int = window.transcript.size()
	window._scroll_to_latest(window._generation)
	assert(window.transcript.size() == count, "History navigation is read-only")
	window.advance()
	window.advance()
	assert(closes == 1)
	assert(not window.is_open())
	assert(window.open_event(data, "second") == OK)
	window.advance()
	window.advance()
	window.advance()
	window.select_choice("ask")
	assert(window.transcript[4].text.contains("餐桌"))
	window.advance()
	window.advance()
	window.advance()
	assert(requests == 2)
	assert(window.acknowledge_reward(request_id, true))
	window.advance()
	assert(closes == 2)
	# Host simulation: repeated requests must not duplicate awards.
	var demo = load("res://demo/demo.tscn").instantiate()
	root.add_child(demo)
	await process_frame
	demo.start_event()
	var ui = demo.event_window
	ui.advance()
	ui.advance()
	ui.advance()
	ui.select_choice("take")
	ui.advance()
	ui.advance()
	assert(demo.mana == 420)
	assert(demo.unlocked_runes.size() == 4)
	demo._on_reward_requested(ui._request, [{"type": "mana", "id": "mana", "amount": 100}])
	assert(demo.mana == 420, "Host ledger prevents duplicate awards")
	ui.advance()
	demo.start_event()
	assert(not ui.is_open(), "Completed demo cannot re-trigger")
	demo.reset_demo()
	assert(demo.mana == 320 and not demo.completed)
	window.queue_free()
	demo.queue_free()
	await process_frame
	print("SCROLLING_EVENT_VALIDATION_PASSED")
	quit(0)
