extends SceneTree
const BIRD = preload("res://Scenes/Creatures/Characters/Generate_Bird.tscn")
const PLAYER = preload("res://Scenes/Player/Controller.tscn")
func _initialize() -> void: call_deferred("run")
func settle() -> void:
	for frame: int in range(4): await process_frame
func run() -> void:
	var bird := BIRD.instantiate()
	var player := PLAYER.instantiate()
	bird.add_child(player)
	root.add_child(bird)
	await settle()
	assert(player.get_controlled_character()==bird,"Child Controller must wait for generated physics and attach automatically")
	assert(player._movement.get_leg_parts().size()==2 and player._movement.command_source==player)
	Input.action_press("Right")
	player._physics_process(1.0/60.0)
	assert(player.get_movement_direction().is_equal_approx(Vector3.RIGHT))
	Input.action_release("Right")
	player.detach_character()
	assert(not player.is_attached())
	assert(bird.generate_creature())
	assert(not player.is_attached(),"Later regeneration must not undo a deliberate detach")
	player.queue_free()
	bird.queue_free()
	await settle()
	var invalid := BIRD.instantiate()
	invalid.get_node("BirdGenerator").body_length = 0.0
	var waiting := PLAYER.instantiate()
	invalid.add_child(waiting)
	root.add_child(invalid)
	await settle()
	assert(not waiting.is_attached() and waiting._pending_initial_character==null,"Failed generation must release the pending attachment")
	waiting.queue_free()
	invalid.queue_free()
	await settle()
	var free_player := PLAYER.instantiate()
	root.add_child(free_player)
	await settle()
	assert(not free_player.is_attached() and free_player._pending_initial_character==null,"Unparented Controller must still start freely")
	free_player.queue_free()
	await settle()
	print("GENERATED_CONTROLLER_INITIALIZATION_PASSED")
	quit()
