extends SceneTree
const CHARACTER = preload("res://Scripts/Creatures/PhysicalCharacterController.gd")
const PART = preload("res://Scenes/Creatures/Bodyparts/PhysicalTestCreatureParts/TestCreature_Part.tscn")
const SPRING = preload("res://Scripts/Creatures/SegmentDistanceSpring3D.gd")
func _initialize() -> void: call_deferred("run")
func body(actor: Node, name: String, tag: int) -> PhysicalBodyPart3D:
	var part := PART.instantiate() as PhysicalBodyPart3D
	part.name = name
	part.tags.clear()
	part.tags.append(tag)
	part.freeze = true
	actor.add_child(part)
	return part
func link(actor: Node, first: String, second: String, spring: bool = false) -> Node:
	var joint: Node = SPRING.new() if spring else PinJoint3D.new()
	joint.name = first+"_"+second
	joint.node_a = NodePath("../"+first)
	joint.node_b = NodePath("../"+second)
	actor.add_child(joint)
	return joint
func fixture() -> Node3D:
	var actor := CHARACTER.new()
	body(actor,"Head",3)
	body(actor,"Neck",5)
	body(actor,"Torso",0)
	body(actor,"Leg",1)
	link(actor,"Head","Neck")
	link(actor,"Neck","Torso")
	link(actor,"Torso","Leg")
	return actor
func settle() -> void:
	for frame: int in range(4): await process_frame
func run() -> void:
	var actor := fixture()
	root.add_child(actor)
	await settle()
	assert(actor.has_node("CharacterDamageController3D"),"Base character must ensure an integrity coordinator")
	for name: String in ["Head","Neck","Torso","Leg"]:
		assert(not actor.get_node(name).is_broken,"Indirect Head/Torso connectivity must preserve the whole chain")
	actor.get_node("Torso_Leg").queue_free()
	await settle()
	assert(actor.get_node("Leg").is_broken and actor.get_node("Leg").current_hp==0.0)
	assert(not actor.get_node("Torso").is_broken and not actor.get_node("Head").is_broken)
	actor.get_node("Neck").break_part()
	await settle()
	for name: String in ["Head","Neck","Torso","Leg"]: assert(actor.get_node(name).is_broken)
	assert(actor.get_node("CharacterDamageController3D").is_character_disabled())
	actor.queue_free()
	await settle()
	var islands := fixture()
	body(islands,"Torso_NoHead",0)
	body(islands,"Leg_NoHead",1)
	link(islands,"Torso_NoHead","Leg_NoHead")
	body(islands,"Head_NoTorso",3)
	body(islands,"Wing_NoTorso",7)
	link(islands,"Head_NoTorso","Wing_NoTorso")
	body(islands,"Head_Second",3)
	body(islands,"Torso_Second",0)
	link(islands,"Head_Second","Torso_Second")
	root.add_child(islands)
	await settle()
	for name: String in ["Torso_NoHead","Leg_NoHead","Head_NoTorso","Wing_NoTorso"]: assert(islands.get_node(name).is_broken)
	for name: String in ["Head","Torso","Leg","Head_Second","Torso_Second"]: assert(not islands.get_node(name).is_broken)
	assert(not islands.get_node("CharacterDamageController3D").is_character_disabled())
	islands.queue_free()
	await settle()
	var segmented := fixture()
	body(segmented,"Torso_Back",0)
	link(segmented,"Torso","Torso_Back",true)
	root.add_child(segmented)
	await settle()
	assert(not segmented.get_node("Torso_Back").is_broken,"Segment springs must count as body connections")
	segmented.get_node("Torso_Torso_Back").queue_free()
	await settle()
	assert(segmented.get_node("Torso_Back").is_broken,"Removing a spring must invalidate a headless segment")
	assert(not segmented.get_node("Torso").is_broken)
	segmented.queue_free()
	await settle()
	var headless := CHARACTER.new()
	body(headless,"Torso",0)
	root.add_child(headless)
	await settle()
	assert(headless.get_node("Torso").is_broken and headless.get_node("CharacterDamageController3D").is_character_disabled())
	headless.queue_free()
	await settle()
	print("CHARACTER_BODY_INTEGRITY_PASSED")
	quit()
