const assert=require('node:assert/strict');
const S=require('../schema.js');require('../seed.js');const M=require('../model.js');
let p=M.normalize(globalThis.EventSeed);
assert.equal(p.tables.events.length,7);
assert.deepEqual(p.tables.goals.filter(r=>r.type==='献祭').map(r=>r.quantity),[3,7,1]);
assert.equal(p.tables.actions.find(r=>r.type==='设置天气').scope,'cell_blood_altar');
assert.equal(M.validate(p).filter(i=>i.level==='error').length,0);
const event='QST_SIDE_003_001';
M.rename(p,'events',event,'EVENT_BLOOD');p.tables.events.find(e=>e.id===event).id='EVENT_BLOOD';
assert(p.tables.goals.every(r=>r.event_id==='EVENT_BLOOD'));
assert(p.tables.conditions.find(r=>r.field==='EVENT_BLOOD.status'));
assert.equal(p.tables.actions.find(r=>r.type==='完成事件').target,'EVENT_BLOOD');
const clone=M.cloneEvent(p,'EVENT_BLOOD');assert.notEqual(clone,'EVENT_BLOOD');
assert.equal(p.tables.goals.filter(r=>r.event_id===clone).length,4);
assert.equal(M.validate(p).filter(i=>i.level==='error').length,0);
const oldNode=p.tables.nodes[0].id;M.rename(p,'nodes',oldNode,'D_RENAMED');p.tables.nodes[0].id='D_RENAMED';assert.equal(p.tables.events.find(r=>r.id==='EVENT_BLOOD').start_node,'D_RENAMED');
assert.throws(()=>M.rename(p,'nodes','D_RENAMED','中文 ID'));
const snapshot=M.copy(p);snapshot.tables.nodes[0].next_node='MISSING';assert(M.validate(snapshot).some(i=>i.level==='error'&&i.field==='next_node'));
const q=M.copy(p);q.tables.actions[1].once_key=q.tables.actions[0].once_key;assert(M.validate(q).some(i=>i.field==='once_key'));
const badBool=M.copy(p);badBool.tables.conditions.find(r=>r.value_type==='BOOL').value='yes';assert(M.validate(badBool).some(i=>i.field==='value'));
const badQuantity=M.copy(p);badQuantity.tables.goals[1].quantity=2.5;assert(M.validate(badQuantity).some(i=>i.field==='quantity'));
const sheets=Object.entries(S).map(([key,s])=>({name:s.label,rows:[s.fields.map(f=>f.label),...p.tables[key].map(r=>s.fields.map(f=>r[f.key]))]}));assert.deepEqual(M.fromSheets(sheets).tables,p.tables);
const old=M.fromSheets([{name:'工作表1',rows:[['事件名','概览','地点',null,'奖励','效果','需要内容'],['旧事件','故事','小屋',null,'100魔力','作用','立绘'],[null,null,'角色','你好', '增加100魔力'],[null,null,'玩家选项','好的']]}]);
assert.equal(old.tables.events.length,1);assert.equal(old.tables.nodes.length,2);assert.equal(old.tables.events[0].source_reward,'100魔力');assert(old.tables.nodes[1].note.includes('手动转为选项'));assert.equal(old.tables.nodes[0].next_node,old.tables.nodes[1].id);
assert.throws(()=>M.normalize({schema_version:99,tables:{events:[]}}));
assert.throws(()=>M.normalize({tables:{events:[{id:'EVENT_1',name:{}}]}}));
const cycle=M.normalize(globalThis.EventSeed);cycle.tables.nodes[2].next_node=cycle.tables.nodes[0].id;assert(M.validate(cycle).some(i=>i.message.includes('循环')));
const ready=M.normalize(globalThis.EventSeed);ready.tables.events.find(r=>r.id===event).status='可发布';assert(M.validate(ready).some(i=>i.table==='maps'&&i.level==='error'));
console.log('PASS: seed, blood quantities/scope, ID references, cloning, types, duplicates, import round-trip, legacy drafts, cycles, publish gate.');
