'use strict';
const $=id=>document.getElementById(id);
const TYPES={head:'头',body:'身',arm:'手',foot:'脚',wing:'翅膀'};
const PORTS={neck:'头部',armL:'左手',armR:'右手',footL:'左脚',footR:'右脚',wingL:'左翼',wingR:'右翼'};
const CONFIG={schemaVersion:1,maxFileBytes:15*1024*1024,maxParts:60,bodyWidth:200,storageKey:'monster-assembly-v01',defaults:{head:{width:135,z:30,anchor:[.5,.75]},body:{width:200,z:10,anchor:[.5,.5]},arm:{width:92,z:20,anchor:[.5,.1]},foot:{width:90,z:5,anchor:[.5,.08]},wing:{width:190,z:-10,anchor:[.88,.75]}},ports:{neck:[.5,.1],armL:[.12,.3],armR:[.88,.3],footL:[.3,.87],footR:[.7,.87],wingL:[.15,.25],wingR:[.85,.25]}};
const canvas=$('canvas'),ctx=canvas.getContext('2d');
let state,selected=null,undo=[],redo=[],images=new Map(),view={scale:1,x:0,y:0},drag=null,pan=null,raf=0;
const clone=v=>JSON.parse(JSON.stringify(v));
const uid=()=>globalThis.crypto?.randomUUID?.()||'id-'+Date.now()+'-'+Math.random().toString(16).slice(2);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function svgAsset(type,variant=0){
 const colors={head:['#ca9876','#9ea9b4'],body:['#869779','#b59779'],arm:['#b8a17b','#849b93'],foot:['#9b9275','#a78872'],wing:['#bab8a0','#8fa3a8']};
 const shapes={body:'<path d="M55 24Q100 5 145 24L158 146Q125 188 100 180Q65 184 42 146Z"/><path d="M65 57L135 57M60 120L140 120" fill="none"/>',head:variant?'<path d="M45 120L35 57L50 16L72 42L128 42L152 16L169 60L151 119L105 150Z"/><path d="M61 73L90 84M117 84L145 72" stroke="#e9d9b3" stroke-width="8"/>':'<path d="M60 144L36 85L48 37L72 15L78 50L130 48L154 18L153 71L165 116L123 149Z"/><path d="M99 96L141 96L156 115L130 129L96 123Z" fill="#dcccaa"/><circle cx="79" cy="78" r="7" fill="#273338"/>',arm:'<path d="M76 12L124 12L143 55L113 102L126 158L96 180L58 159L74 103L52 59Z"/><path d="M72 100L116 100"/>',foot:'<path d="M72 10L121 10L131 107L170 138L167 176L47 176L39 144L68 105Z"/><path d="M72 144L72 171M104 144L104 172M139 148L139 172"/>',wing:variant?'<path d="M177 147L135 36L68 18L19 46L6 105L68 78L96 138Z"/><path d="M176 147L69 18M176 147L19 46M176 147L6 105"/>':'<path d="M178 150L144 53L91 22L43 26L18 47L6 97L51 72L63 111L94 91L112 132L143 116Z"/><path d="M178 150L43 26M178 150L18 47M178 150L6 97"/>'};
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200" viewBox="0 0 200 200"><g fill="${colors[type][variant]}" stroke="#303d3c" stroke-width="6" stroke-linejoin="round">${shapes[type]}</g></svg>`;
 return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);
}
function initial(){const assets=[];for(const type of Object.keys(TYPES))for(let v=0;v<2;v++)assets.push({id:uid(),type,name:TYPES[type]+'·示例'+(v?' B':' A'),src:svgAsset(type,v),ratio:1});return{schema:'monster-assembly',version:1,assets,parts:[],log:[]};}
function asset(id){return state.assets.find(a=>a.id===id)}
function part(){return state.parts.find(p=>p.id===selected)}
function body(){return state.parts.find(p=>p.type==='body')}
function log(action){state.log.push({at:new Date().toISOString(),action});state.log=state.log.slice(-500)}
function checkpoint(){undo.push(JSON.stringify(state));undo=undo.slice(-40);redo=[];}
function change(action,fn){checkpoint();fn();log(action);refresh();persist();}
function persist(){try{localStorage.setItem(CONFIG.storageKey,JSON.stringify(state));$('storageStatus').textContent='已自动保存于当前浏览器；请导出方案作为可靠备份。'}catch(e){$('storageStatus').textContent='本机缓存不可用或容量不足；请导出方案保存，不影响当前操作。'}}
function say(s){$('status').textContent=s}
function imageFor(src){if(!images.has(src)){const im=new Image();im.onload=draw;im.onerror=()=>say('某个素材无法读取，请替换此素材。');im.src=src;images.set(src,im)}return images.get(src)}
function rootTransform(p){const a=asset(p.assetId),h=p.width*(a?.ratio||1)*(p.heightScale||1),angle=p.rotation*Math.PI/180;return{x:p.x||0,y:p.y||0,w:p.width,h,angle,mirror:p.mirror};}
function point(tr,u,v){const xx=(u-.5)*tr.w*(tr.mirror?-1:1),yy=(v-.5)*tr.h;return{x:tr.x+xx*Math.cos(tr.angle)-yy*Math.sin(tr.angle),y:tr.y+xx*Math.sin(tr.angle)+yy*Math.cos(tr.angle)}}
function transform(p){const tr=rootTransform(p);if(p.type==='body')return tr;const b=body();if(b){const port=b.ports[p.mount]||[.5,.5],target=point(rootTransform(b),...port);const anchor=point({...tr,x:0,y:0},p.anchor[0],p.anchor[1]);tr.x=target.x-anchor.x+p.offsetX;tr.y=target.y-anchor.y+p.offsetY;}else{tr.x=p.offsetX;tr.y=p.offsetY}return tr;}
function sorted(){return [...state.parts].sort((a,b)=>a.z-b.z)}
function mountFor(type){const choices={head:['neck'],arm:['armL','armR'],foot:['footL','footR'],wing:['wingL','wingR']}[type]||[];return choices.find(m=>!state.parts.some(p=>p.mount===m))||choices[0]||''}
function addAsset(id){const a=asset(id);if(!a)return;if(a.type!=='body'&&!body()){say('请先添加身体，它提供自动连接接口。');return}if(a.type==='body'&&body()){const b=body();change('替换身体素材：'+a.name,()=>{b.assetId=id;b.name=a.name;selected=b.id});return}if(state.parts.length>=CONFIG.maxParts){say('最多支持 '+CONFIG.maxParts+' 个部件。');return}const def=CONFIG.defaults[a.type],mount=mountFor(a.type);change('添加组件：'+a.name,()=>{const p={id:uid(),type:a.type,name:a.name,assetId:id,width:def.width,rotation:0,offsetX:0,offsetY:0,z:def.z,mirror:mount.endsWith('R'),anchor:clone(def.anchor),mount,x:0,y:0};if(a.type==='body')p.ports=clone(CONFIG.ports);state.parts.push(p);selected=p.id});}
function renderLists(){const library=$('assets');library.replaceChildren();for(const a of state.assets.filter(a=>a.type===$('assetType').value)){const el=document.createElement('div');el.className='asset';const img=document.createElement('img');img.src=a.src;img.alt=a.name;const row=document.createElement('div'),name=document.createElement('span'),btn=document.createElement('button');name.textContent=a.name;btn.textContent=a.type==='body'&&body()?'替换身体':'添加到组合';btn.onclick=()=>addAsset(a.id);row.append(name,btn);el.append(img,row);library.append(el)}const list=$('parts');list.replaceChildren();for(const p of sorted().reverse()){const btn=document.createElement('button');btn.className='part'+(p.id===selected?' active':'');const text=document.createElement('b');text.textContent=p.name;const z=document.createElement('span');z.textContent='层 '+p.z;btn.append(text,z);btn.onclick=()=>{selected=p.id;refresh()};list.append(btn)}$('partCount').textContent=state.parts.length+' 件';$('empty').hidden=state.parts.length>0;const ol=$('log');ol.replaceChildren();for(const entry of state.log.slice(-12).reverse()){const li=document.createElement('li');li.textContent=new Date(entry.at).toLocaleTimeString()+' '+entry.action;ol.append(li)}$('undo').disabled=!undo.length;$('redo').disabled=!redo.length;}
function editor(){const p=part();$('editor').hidden=!p;$('noSelection').hidden=!!p;if(!p)return;for(const key of ['name','width','rotation','offsetX','offsetY','z'])$(key).value=p[key];if(p.type==='body'){$('offsetX').value=p.x;$('offsetY').value=p.y}$('mirror').checked=p.mirror;$('anchorX').value=p.anchor[0];$('anchorY').value=p.anchor[1];$('bodyPorts').hidden=p.type!=='body';const mount=$('mount');mount.replaceChildren();const choices=p.type==='body'?{'':'身体根节点'}:Object.fromEntries(Object.entries(PORTS).filter(([k])=>p.type==='head'?k==='neck':k.startsWith(p.type==='arm'?'arm':p.type==='foot'?'foot':'wing')));for(const [key,value]of Object.entries(choices)){const o=document.createElement('option');o.value=key;o.textContent=value;$('mount').append(o)}mount.value=p.mount;mount.disabled=p.type==='body';if(p.type==='body'){if(!$('portSelect').options.length)for(const[key,value]of Object.entries(PORTS)){const o=document.createElement('option');o.value=key;o.textContent=value;$('portSelect').append(o)}portEditor();}}
function portEditor(){const p=part();if(p?.type==='body'){const v=p.ports[$('portSelect').value];$('portX').value=v[0];$('portY').value=v[1];}}
function refresh(){renderLists();editor();draw();}
function canvasSize(){const r=canvas.getBoundingClientRect();const dpr=window.devicePixelRatio||1;canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);draw()}
function stageTransform(context,width,height,scale=view.scale){context.translate(width/2+view.x,height/2+view.y);context.scale(scale,scale)}
function paint(context,selection=true){for(const p of sorted()){const tr=transform(p),im=imageFor(asset(p.assetId)?.src||'');context.save();context.translate(tr.x,tr.y);context.rotate(tr.angle);context.scale(tr.mirror?-1:1,1);if(im.complete&&im.naturalWidth)context.drawImage(im,-tr.w/2,-tr.h/2,tr.w,tr.h);if(selection&&($('showBounds').checked||p.id===selected)){context.strokeStyle=p.id===selected?'#d99333':'#5e777b';context.lineWidth=1.5/view.scale;context.setLineDash([6,4]);context.strokeRect(-tr.w/2,-tr.h/2,tr.w,tr.h)}context.restore();}if(selection&&$('showAnchors').checked){const b=body();if(b)for(const [key,uv]of Object.entries(b.ports)){const target=point(rootTransform(b),...uv);context.beginPath();context.arc(target.x,target.y,5,0,Math.PI*2);context.fillStyle='#e6b653';context.fill();context.strokeStyle='#34443f';context.stroke();}const p=part();if(p&&p.type!=='body'){const tr=transform(p),a=point(tr,...p.anchor);context.strokeStyle='#b36845';context.beginPath();context.moveTo(a.x-8,a.y);context.lineTo(a.x+8,a.y);context.moveTo(a.x,a.y-8);context.lineTo(a.x,a.y+8);context.stroke();}}}
function draw(){if(!state)return;const dpr=window.devicePixelRatio||1,w=canvas.width/dpr,h=canvas.height/dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const bg=$('background').value;ctx.fillStyle=bg==='dark'?'#24313b':'#ded8c7';ctx.fillRect(0,0,w,h);if(bg==='check')for(let x=0;x<w;x+=20)for(let y=0;y<h;y+=20){ctx.fillStyle=(x/20+y/20)%2?'#ccd0c9':'#eef0e9';ctx.fillRect(x,y,20,20)}ctx.save();stageTransform(ctx,w,h);paint(ctx);ctx.restore();}
function pointer(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left-r.width/2-view.x)/view.scale,y:(e.clientY-r.top-r.height/2-view.y)/view.scale};}
function hit(p,pt){const tr=transform(p),dx=pt.x-tr.x,dy=pt.y-tr.y;const x=(dx*Math.cos(tr.angle)+dy*Math.sin(tr.angle))*(tr.mirror?-1:1)+tr.w/2,y=-dx*Math.sin(tr.angle)+dy*Math.cos(tr.angle)+tr.h/2;if(x<0||y<0||x>tr.w||y>tr.h)return false;const im=imageFor(asset(p.assetId).src);if(!im.complete)return false;try{const temp=document.createElement('canvas');temp.width=im.naturalWidth;temp.height=im.naturalHeight;const c=temp.getContext('2d');c.drawImage(im,0,0);return c.getImageData(Math.min(temp.width-1,Math.floor(x/tr.w*temp.width)),Math.min(temp.height-1,Math.floor(y/tr.h*temp.height)),1,1).data[3]>20}catch(e){return true}}
function beginPan(e){e.preventDefault();pan={id:e.pointerId,startX:e.clientX,startY:e.clientY,x:view.x,y:view.y};canvas.style.cursor='grabbing';canvas.setPointerCapture(e.pointerId);}
canvas.addEventListener('pointerdown',e=>{if(pan||drag)return;if(e.button===1){beginPan(e);return}if(e.button!==0)return;const pt=pointer(e),p=sorted().reverse().find(p=>hit(p,pt));if(!p){beginPan(e);return}selected=p.id;checkpoint();drag={id:p.id,start:pt,x:!p.parentId?p.x:p.offsetX,y:!p.parentId?p.y:p.offsetY,moved:false};canvas.setPointerCapture(e.pointerId);refresh()});
canvas.addEventListener('pointermove',e=>{if(pan){if(e.pointerId!==pan.id)return;view.x=pan.x+e.clientX-pan.startX;view.y=pan.y+e.clientY-pan.startY;draw();return}if(!drag)return;const p=state.parts.find(p=>p.id===drag.id),pt=pointer(e);const dx=pt.x-drag.start.x,dy=pt.y-drag.start.y;drag.moved=drag.moved||Math.abs(dx)+Math.abs(dy)>2;if(!p.parentId){p.x=clamp(drag.x+dx,-2000,2000);p.y=clamp(drag.y+dy,-2000,2000)}else{p.offsetX=clamp(drag.x+dx,-1000,1000);p.offsetY=clamp(drag.y+dy,-1000,1000)}draw();});
function endDrag(e){if(pan){if(e&&e.pointerId!==pan.id)return;pan=null;canvas.style.cursor='';draw();return}if(!drag)return;if(drag.moved){log('拖动微调：'+part().name);persist()}else undo.pop();drag=null;refresh()}
canvas.addEventListener('pointerup',endDrag);canvas.addEventListener('pointercancel',endDrag);
canvas.addEventListener('lostpointercapture',endDrag);
canvas.addEventListener('auxclick',e=>{if(e.button===1)e.preventDefault()});
canvas.addEventListener('wheel',e=>{e.preventDefault();view.scale=clamp(view.scale*Math.exp(-e.deltaY*.001),.25,3);draw()}, {passive:false});
for(const key of ['name','width','rotation','offsetX','offsetY','z','mirror','anchorX','anchorY','mount'])$(key).addEventListener('change',()=>{const p=part();if(!p)return;change('修改 '+p.name+' / '+key,()=>{if(key==='name')p.name=$('name').value.trim()||TYPES[p.type];else if(key==='mirror')p.mirror=$('mirror').checked;else if(key==='mount')p.mount=$('mount').value;else if(key.startsWith('anchor'))p.anchor[key==='anchorX'?0:1]=clamp(Number($(key).value)||0,0,1);else{const ranges={width:[10,1000],rotation:[-180,180],z:[-100,100],offsetX:[-1000,1000],offsetY:[-1000,1000]};const value=clamp(Number($(key).value)||0,...ranges[key]);if(p.type==='body'&&(key==='offsetX'||key==='offsetY'))p[key==='offsetX'?'x':'y']=value;else p[key]=value}})});
$('portSelect').onchange=portEditor;for(const key of ['portX','portY'])$(key).onchange=()=>{const p=part();if(p?.type==='body')change('调整身体接口 '+$('portSelect').value,()=>{p.ports[$('portSelect').value][key==='portX'?0:1]=clamp(Number($(key).value)||0,0,1)})};
function download(data,name,type='application/json'){const blob=data instanceof Blob?data:new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function filename(name){return(name||'组件').replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').slice(0,60)}
function pick(accept,callback){const input=$('fileInput');input.value='';input.accept=accept;input.onchange=async()=>{const file=input.files[0];if(!file)return;if(file.size>CONFIG.maxFileBytes){say('文件过大；上限 15 MB，请先压缩素材。');return}try{await callback(file)}catch(e){say('导入失败：'+e.message)}};input.click()}
function readImage(file){return new Promise((resolve,reject)=>{if(!['image/png','image/jpeg','image/webp'].includes(file.type)){reject(new Error('请选择 PNG、JPG 或 WebP 图片'));return}const fr=new FileReader();fr.onload=()=>{const im=new Image();im.onload=()=>resolve({src:fr.result,ratio:im.height/im.width});im.onerror=()=>reject(new Error('图片无法读取'));im.src=fr.result};fr.onerror=()=>reject(new Error('文件读取失败'));fr.readAsDataURL(file)})}
async function upload(file,replace=false){const info=await readImage(file),p=part(),type=replace&&p?p.type:$('assetType').value;change((replace?'替换':'导入')+'素材：'+file.name,()=>{const a={id:uid(),type,name:file.name.replace(/\.[^.]+$/,''),...info};state.assets.push(a);if(replace&&p){p.assetId=a.id;p.name=a.name}});say(replace?'已替换素材，保留原接口、尺寸与层级；可微调连接点。':'已添加至素材库，点击「添加到组合」完成连接。')}
function validAsset(a){if(!a||!TYPES[a.type]||typeof a.name!=='string'||a.name.length>200||typeof a.src!=='string'||!/^data:image\/(png|jpeg|webp|svg\+xml)[;,]/.test(a.src)||!Number.isFinite(a.ratio)||a.ratio<=0||a.ratio>100)throw new Error('素材数据或格式不合法');}
function validPart(p){if(!p||!TYPES[p.type]||typeof p.name!=='string'||p.name.length>200)throw new Error('组件类型或名称不合法');for(const [k,min,max]of [['width',10,1000],['rotation',-180,180],['offsetX',-1000,1000],['offsetY',-1000,1000],['z',-100,100],['x',-2000,2000],['y',-2000,2000]])if(!Number.isFinite(p[k])||p[k]<min||p[k]>max)throw new Error('参数越界：'+k);if(!Array.isArray(p.anchor)||p.anchor.length!==2||!p.anchor.every(v=>Number.isFinite(v)&&v>=0&&v<=1))throw new Error('连接点无效');if(p.type!=='body'&&!Object.hasOwn(PORTS,p.mount))throw new Error('接口无效');if(p.type==='body')for(const k of Object.keys(CONFIG.ports)){const v=p.ports?.[k];if(!Array.isArray(v)||v.length!==2||!v.every(n=>Number.isFinite(n)&&n>=0&&n<=1))throw new Error('身体接口无效')}if(typeof p.mirror!=='boolean')throw new Error('翻转参数无效')}
function validateProject(data){if(data.schema!=='monster-assembly'||data.version!==1)throw new Error('方案版本不支持');if(!Array.isArray(data.assets)||data.assets.length>200||!Array.isArray(data.parts)||data.parts.length>60||!Array.isArray(data.log))throw new Error('方案内容无效');data.assets.forEach(validAsset);data.parts.forEach(validPart);if(new Set(data.assets.map(a=>a.id)).size!==data.assets.length||new Set(data.parts.map(p=>p.id)).size!==data.parts.length)throw new Error('重复标识');if(data.parts.some(p=>!data.assets.some(a=>a.id===p.assetId&&a.type===p.type)))throw new Error('素材引用缺失');if(data.parts.filter(p=>p.type==='body').length>1||data.parts.some(p=>p.type!=='body')&&!data.parts.some(p=>p.type==='body'))throw new Error('组合需要一个身体根节点');data.log=data.log.filter(e=>e&&typeof e.at==='string'&&typeof e.action==='string').slice(-500);return data;}
$('assetType').onchange=renderLists;$('uploadAsset').onclick=()=>pick('image/png,image/jpeg,image/webp',f=>upload(f));$('replace').onclick=()=>pick('image/png,image/jpeg,image/webp',f=>upload(f,true));
$('savePart').onclick=()=>{const p=part();if(!p)return;log('导出单个组件：'+p.name);download({schema:'monster-component',version:1,asset:clone(asset(p.assetId)),part:clone(p)},filename(p.name)+'.component.json');refresh();persist();say('组件文件包含图片、连接点、接口、变换和前后层级。')};
$('importPart').onclick=()=>pick('.json',async f=>{const data=JSON.parse(await f.text());if(data.schema!=='monster-component'||data.version!==1)throw new Error('请选择本平台的组件文件');validAsset(data.asset);validPart(data.part);if(data.asset.type!==data.part.type)throw new Error('组件与素材类型不符');if(data.part.type!=='body'&&!body())throw new Error('请先添加身体');if(state.parts.length>=60)throw new Error('组件数超过上限');change('导入组件：'+data.part.name,()=>{const a={...data.asset,id:uid()},p={...data.part,id:uid(),assetId:a.id};state.assets.push(a);if(p.type==='body'&&body()){const prev=body();state.parts=state.parts.filter(x=>x.id!==prev.id)}state.parts.push(p);selected=p.id});say('已导入组件，并恢复连接点、接口与层级。')});
$('saveProject').onclick=()=>{log('导出整只怪物方案');download(state,'怪物方案.monster.json');refresh();persist()};
$('loadProject').onclick=()=>pick('.json',async f=>{const data=validateProject(JSON.parse(await f.text()));if(!confirm('导入会替换当前组合和素材库；可撤销。继续？'))return;change('导入怪物方案：'+f.name,()=>{state=data;selected=body()?.id||null});});
$('snap').onclick=()=>{const p=part();if(p)change('重置连接偏移：'+p.name,()=>{if(p.type==='body'){p.x=0;p.y=0}else{p.offsetX=0;p.offsetY=0}})};
$('duplicate').onclick=()=>{const p=part();if(!p)return;if(p.type==='body'){say('身体作为唯一根节点，不能复制。');return}if(state.parts.length>=60){say('已达到组件数量上限。');return}change('复制组件：'+p.name,()=>{const q={...clone(p),id:uid(),name:p.name+' 副本',offsetX:p.offsetX+20,offsetY:p.offsetY+20};state.parts.push(q);selected=q.id})};
$('deletePart').onclick=()=>{const p=part();if(!p)return;if(p.type==='body'&&state.parts.length>1){say('先删除连接的其它部件，或替换身体素材；避免丢失接口。');return}change('删除组件：'+p.name,()=>{state.parts=state.parts.filter(x=>x.id!==p.id);selected=null})};
function fit(){const pts=[];for(const p of state.parts){const tr=transform(p);for(const u of [0,1])for(const v of [0,1])pts.push(point(tr,u,v))}if(!pts.length){view={scale:1,x:0,y:0};draw();return}const xs=pts.map(p=>p.x),ys=pts.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),r=canvas.getBoundingClientRect();const scale=clamp(Math.min((r.width-70)/(maxX-minX),(r.height-70)/(maxY-minY)),.25,2);view={scale,x:-(minX+maxX)/2*scale,y:-(minY+maxY)/2*scale};draw()}
$('fit').onclick=fit;$('exportPng').onclick=()=>{const c=document.createElement('canvas');c.width=1200;c.height=1200;const cc=c.getContext('2d');cc.translate(600,600);const corners=[];for(const p of state.parts){const tr=transform(p);for(const u of [0,1])for(const v of [0,1])corners.push(point(tr,u,v))}if(corners.length){const xs=corners.map(p=>p.x),ys=corners.map(p=>p.y),x1=Math.min(...xs),x2=Math.max(...xs),y1=Math.min(...ys),y2=Math.max(...ys),s=Math.min(1100/(x2-x1),1100/(y2-y1));cc.scale(s,s);cc.translate(-(x1+x2)/2,-(y1+y2)/2)}paint(cc,false);c.toBlob(blob=>{if(blob)download(blob,'怪物预览.png');say('已导出透明底 PNG；连接点与选择框不导出。')},'image/png')};
$('exportLog').onclick=()=>download({platformVersion:'0.1',entries:state.log},'拼接操作记录.json');
$('undo').onclick=()=>{if(!undo.length)return;redo.push(JSON.stringify(state));state=JSON.parse(undo.pop());selected=null;log('撤销');refresh();persist()};$('redo').onclick=()=>{if(!redo.length)return;undo.push(JSON.stringify(state));state=JSON.parse(redo.pop());selected=null;log('重做');refresh();persist()};
function example(){state=initial();selected=null;for(const type of ['body','head','arm','arm','foot','foot','wing','wing'])addAsset(state.assets.find(a=>a.type===type).id);undo=[];redo=[];log('载入示例怪物');selected=body().id;refresh();persist();requestAnimationFrame(fit)}
$('reset').onclick=()=>{if(confirm('恢复示例将替换当前素材库与组合，请先导出需要保留的方案。')){checkpoint();const before=undo.slice();example();undo=before;refresh()}};
$('help').onclick=()=>window.open('构建逻辑.md','_blank');for(const id of ['showAnchors','showBounds','background'])$(id).onchange=draw;
window.addEventListener('resize',canvasSize);
// Boot is performed by dynamic.js after the v2 migration and connection rules are installed.
