'use strict';
// v2 supports a body forest; every attachment points to a body, with cycle guards.
CONFIG.schemaVersion=2;
// Failed multi-part edits leave the original combination and undo history intact.
change=function(action,fn){const before=clone(state),beforeSelected=selected,beforeUndo=[...undo],beforeRedo=[...redo];try{checkpoint();fn();log(action);refresh();persist();return true}catch(e){state=before;selected=beforeSelected;undo=beforeUndo;redo=beforeRedo;refresh();say('操作未完成，已保留原组合：'+e.message);return false}};
const oldInitial=initial;
initial=function(){const s=oldInitial();s.version=2;return s};
const portKind=k=>k==='neck'?'head':k.startsWith('arm')?'arm':k.startsWith('foot')?'foot':k.startsWith('wing')?'wing':k==='next'?'body':'any';
function bodies(){return state.parts.filter(p=>p.type==='body')}
body=function(){const p=part();return p?.type==='body'?p:state.parts.find(b=>b.id===p?.parentId)||bodies()[0]};
function descendants(id){const set=new Set([id]);let added=true;while(added){added=false;for(const p of state.parts)if(p.parentId&&set.has(p.parentId)&&!set.has(p.id)){set.add(p.id);added=true}}return set}
function migrate(data){const s=clone(data);if(s.version===1){const b=s.parts.find(p=>p.type==='body');for(const p of s.parts){p.parentId=p.type==='body'?null:b?.id||null;p.heightScale=1;if(p.type==='body'){p.portNames=Object.fromEntries(Object.keys(p.ports).map(k=>[k,PORTS[k]||k]));p.portTypes=Object.fromEntries(Object.keys(p.ports).map(k=>[k,portKind(k)]));}}s.version=2;}return s}
transform=function(p,seen=new Set()){if(seen.has(p.id))throw new Error('连接不能形成循环');seen.add(p.id);const tr=rootTransform(p),parent=state.parts.find(b=>b.id===p.parentId);if(parent){const target=point(transform(parent,seen),...(parent.ports[p.mount]||[.5,.5])),a=point({...tr,x:0,y:0},...p.anchor);tr.x=target.x-a.x+p.offsetX;tr.y=target.y-a.y+p.offsetY;}return tr};
function freshPart(a,patch={}){const d=CONFIG.defaults[a.type];const p={id:uid(),type:a.type,name:a.name,assetId:a.id,width:d.width,heightScale:1,rotation:0,offsetX:0,offsetY:0,z:d.z,mirror:false,anchor:clone(d.anchor),mount:'',parentId:null,x:0,y:0,...patch};if(a.type==='body'){p.ports={};p.portNames={};p.portTypes={};}return p}
function compatible(b,type){return Object.keys(b.ports).filter(k=>b.portTypes[k]===type||b.portTypes[k]==='any')}
function newPort(b,type='any',xy=[.5,.5]){if(Object.keys(b.ports).length>=40)throw new Error('单躯干最多 40 个连接点');const k='point_'+uid();b.ports[k]=xy;b.portNames[k]=(TYPES[type]||'自由')+'连接点 '+Object.keys(b.ports).length;b.portTypes[k]=type;return k}
function availablePort(b,type){const choices=compatible(b,type),free=choices.find(k=>!state.parts.some(p=>p.parentId===b.id&&p.mount===k));if(free)return free;if(Object.keys(b.ports).length>=40){if(choices.length)return choices[0];throw new Error('请先腾出连接点，或调整已有连接点类型')}const n=state.parts.filter(p=>p.parentId===b.id&&p.type===type).length;const xy=type==='body'?[.8,.5]:type==='head'?[.2+.6*((n%5)/4),.1]:type==='foot'?[.15+.7*((n%6)/5),.88]:[n%2?.88:.12,.2+.12*(Math.floor(n/2)%5)];return newPort(b,type,xy)}
function addRaw(id,parent=body(),patch={}){const a=asset(id);if(state.parts.length>=CONFIG.maxParts)throw new Error('组合最多 60 件');if(!a)return null;const p=freshPart(a,patch);if(parent&&a.type==='body'&&!patch.mount){const tr=transform(parent);p.x=clamp(tr.x+(tr.w+p.width)*.55,-2000,2000);p.y=clamp(tr.y,-2000,2000);}else if(parent){if(patch.mount&&!parent.ports[patch.mount])throw new Error('指定连接点不存在');p.parentId=parent.id;p.mount=patch.mount||availablePort(parent,a.type);p.mirror=patch.mirror??(a.type!=='body'&&p.mount.endsWith('R'));if(a.type==='body'){p.anchor=patch.anchor||[.2,.5];p.width=patch.width??parent.width;p.heightScale=patch.heightScale??parent.heightScale}}state.parts.push(p);return p}
addAsset=function(id){const a=asset(id);if(!a)return;if(a.type!=='body'&&!body()){say('请先添加躯干。');return}if(state.parts.length>=CONFIG.maxParts){say('组合最多 60 件');return}change('添加 '+a.name,()=>{selected=addRaw(id,a.type==='body'?bodies().at(-1):body()).id});fit()};
const oldLists=renderLists;
renderLists=function(){oldLists();$('bodyCount').value=bodies().length;for(const btn of $('assets').querySelectorAll('button'))btn.textContent='添加到组合';};
function options(el,items,value){el.replaceChildren();for(const[k,name]of items){const o=document.createElement('option');o.value=k;o.textContent=name;el.append(o)}el.value=value}
editor=function(){const p=part();$('editor').hidden=!p;$('noSelection').hidden=!!p;if(!p)return;for(const k of ['name','width','rotation','z','heightScale'])$(k).value=p[k];$('offsetX').value=p.parentId?p.offsetX:p.x;$('offsetY').value=p.parentId?p.offsetY:p.y;$('mirror').checked=p.mirror;$('anchorX').value=p.anchor[0];$('anchorY').value=p.anchor[1];const blocked=descendants(p.id);options($('parentBody'),[['','自由放置 / 根节点'],...bodies().filter(b=>!blocked.has(b.id)).map(b=>[b.id,b.name])],p.parentId||'');const parent=state.parts.find(b=>b.id===p.parentId);options($('mount'),parent?compatible(parent,p.type).map(k=>[k,parent.portNames[k]||k]):[['','未连接']],p.mount);$('mount').disabled=!parent;$('bodyPorts').hidden=p.type!=='body';if(p.type==='body'){const old=$('portSelect').value,keys=Object.keys(p.ports);options($('portSelect'),keys.map(k=>[k,p.portNames[k]||k]),keys.includes(old)?old:keys[0]||'');$('portCount').textContent=keys.length+' 个';portEditor();for(const type of ['head','arm','foot','wing'])$(type+'Count').value=state.parts.filter(q=>q.parentId===p.id&&q.type===type).length;}};
portEditor=function(){const p=part(),k=$('portSelect').value,v=p?.ports?.[k];for(const id of ['portX','portY','portName','portType','deletePort'])$(id).disabled=!v;if(v){$('portX').value=v[0];$('portY').value=v[1];$('portName').value=p.portNames[k];$('portType').value=p.portTypes[k];}else{$('portX').value='';$('portY').value='';$('portName').value=''}};
// Replace v1 change listeners without duplicate handlers.
for(const k of ['name','width','rotation','offsetX','offsetY','z','mirror','anchorX','anchorY','mount']){const old=$(k),replacement=old.cloneNode(true);old.replaceWith(replacement)}
for(const k of ['name','width','rotation','offsetX','offsetY','z','mirror','anchorX','anchorY','mount','heightScale'])$(k).addEventListener('change',()=>{const p=part();if(!p)return;change('调整 '+p.name+' / '+k,()=>{if(k==='name')p.name=$(k).value.trim()||TYPES[p.type];else if(k==='mirror')p.mirror=$(k).checked;else if(k==='mount')p.mount=$(k).value;else if(k.startsWith('anchor'))p.anchor[k==='anchorX'?0:1]=clamp(Number($(k).value)||0,0,1);else{const limits={width:[10,1000],heightScale:[.2,4],rotation:[-180,180],z:[-100,100],offsetX:[-1000,1000],offsetY:[-1000,1000]},value=clamp(Number($(k).value)||0,...limits[k]);if(!p.parentId&&k.startsWith('offset'))p[k==='offsetX'?'x':'y']=value;else p[k]=value}})});
function detach(p){const tr=transform(p);p.parentId=null;p.mount='';p.x=tr.x;p.y=tr.y;p.offsetX=0;p.offsetY=0}
$('parentBody').onchange=()=>{const p=part(),b=state.parts.find(b=>b.id===$('parentBody').value);if(!p)return;if(b&&descendants(p.id).has(b.id)){say('不能连接到自身或后代');return}change('修改父躯干：'+p.name,()=>{if(b){p.parentId=b.id;p.mount=availablePort(b,p.type);p.offsetX=0;p.offsetY=0}else detach(p)})};
$('portSelect').onchange=()=>{portEditor();draw()};
for(const k of ['portX','portY','portName','portType'])$(k).onchange=()=>{const p=part(),port=$('portSelect').value;if(!p?.ports[port])return;const value=$(k).value;if(k==='portType'&&state.parts.some(q=>q.parentId===p.id&&q.mount===port&&value!=='any'&&q.type!==value)){say('此连接点已有不同类型部件，请先改挂或删除部件。');portEditor();return}change('调整连接点：'+p.portNames[port],()=>{if(k==='portName')p.portNames[port]=value.trim()||'连接点';else if(k==='portType')p.portTypes[port]=value;else p.ports[port][k==='portX'?0:1]=clamp(Number(value)||0,0,1)})};
$('addPort').onclick=()=>{const p=part();if(p?.type!=='body')return;if(Object.keys(p.ports).length>=40){say('单躯干最多 40 个连接点');return}let key;change('新增躯干连接点',()=>{key=newPort(p,$('portType').value||'any')});$('portSelect').value=key;portEditor();draw()};
$('deletePort').onclick=()=>{const p=part(),k=$('portSelect').value;if(!p?.ports[k])return;change('删除连接点：'+p.portNames[k],()=>{for(const q of state.parts.filter(q=>q.parentId===p.id&&q.mount===k))detach(q);delete p.ports[k];delete p.portNames[k];delete p.portTypes[k]});say('已删点；原所挂部件保留在原位置，现为自由放置。')};
function removeTree(id){const ids=descendants(id);state.parts=state.parts.filter(p=>!ids.has(p.id));if(ids.has(selected))selected=null}
function targetCount(type,n,parent){const current=state.parts.filter(p=>p.type===type&&(type==='body'||p.parentId===parent.id));if(n>current.length&&state.parts.length+n-current.length>60){say('组合最多 60 件');return}if(n<current.length&&type==='body'&&!confirm('减少躯干会移除该段及其所挂部件，可撤销。继续？'))return;change('设置 '+TYPES[type]+'数量为 '+n,()=>{for(const p of current.slice(n).reverse())removeTree(p.id);for(let i=current.length;i<n;i++){const a=state.assets.find(a=>a.type===type);if(!a)break;addRaw(a.id,type==='body'?bodies().at(-1):parent)}if(type==='body')selected=bodies().at(-1)?.id||null});fit()}
$('bodyCount').onchange=()=>targetCount('body',clamp(Math.round(Number($('bodyCount').value)||1),1,20),null);
for(const type of ['head','arm','foot','wing'])$(type+'Count').onchange=()=>{const p=part();if(p?.type==='body')targetCount(type,clamp(Math.round(Number($(type+'Count').value)||0),0,10),p)};
$('duplicate').onclick=()=>{const p=part();if(!p)return;if(state.parts.length>=60){say('组合最多 60 件');return}change('复制组件：'+p.name,()=>{const q={...clone(p),id:uid(),name:p.name+' 副本'};if(q.type==='body'){const tr=transform(p);q.ports={};q.portNames={};q.portTypes={};q.parentId=null;q.mount='';q.offsetX=0;q.offsetY=0;q.x=clamp(tr.x+40,-2000,2000);q.y=clamp(tr.y+20,-2000,2000)}else if(p.parentId){q.offsetX=clamp(p.offsetX+25,-1000,1000);q.offsetY=clamp(p.offsetY+25,-1000,1000)}else{q.x=clamp(p.x+40,-2000,2000);q.y=clamp(p.y+20,-2000,2000)}state.parts.push(q);selected=q.id});fit()};
$('deletePart').onclick=()=>{const p=part();if(!p)return;const n=descendants(p.id).size;if(n>1&&!confirm('删除躯干及其 '+(n-1)+' 个所挂部件，可撤销。继续？'))return;change('删除组件及其子结构：'+p.name,()=>removeTree(p.id));fit()};
$('snap').onclick=()=>{const p=part();if(p)change('重置偏移：'+p.name,()=>{if(p.parentId){p.offsetX=0;p.offsetY=0}else{p.x=0;p.y=0}})};
// Draw all torso points and connection relations, not only the first torso.
const originalPaint=paint;
paint=function(context,selection=true){const checked=$('showAnchors').checked;$('showAnchors').checked=false;originalPaint(context,selection);$('showAnchors').checked=checked;if(!selection||!checked)return;for(const b of bodies()){const tr=transform(b);for(const[k,uv]of Object.entries(b.ports)){const pos=point(tr,...uv);context.beginPath();context.arc(pos.x,pos.y,b.id===selected&&k===$('portSelect').value?7:4,0,Math.PI*2);context.fillStyle=b.id===selected?'#e6b653':'#89a79b';context.fill();context.strokeStyle='#35443d';context.stroke()}}for(const p of state.parts.filter(p=>p.parentId)){const b=state.parts.find(b=>b.id===p.parentId),from=point(transform(b),...b.ports[p.mount]),to=point(transform(p),...p.anchor);context.beginPath();context.moveTo(from.x,from.y);context.lineTo(to.x,to.y);context.strokeStyle='#a8945c';context.setLineDash([3,4]);context.stroke();context.setLineDash([])}};
let portDrag=null;
canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;const b=part();if(b?.type!=='body'||!$('showAnchors').checked)return;const pt=pointer(e),tr=transform(b),key=Object.keys(b.ports).find(k=>{const q=point(tr,...b.ports[k]);return Math.hypot(pt.x-q.x,pt.y-q.y)<10/view.scale});if(!key)return;e.stopImmediatePropagation();checkpoint();portDrag={body:b,key,moved:false};$('portSelect').value=key;portEditor();canvas.setPointerCapture(e.pointerId);draw()},{capture:true});
canvas.addEventListener('pointermove',e=>{if(!portDrag)return;e.stopImmediatePropagation();const b=portDrag.body,tr=transform(b),pt=pointer(e),dx=pt.x-tr.x,dy=pt.y-tr.y,x=(dx*Math.cos(tr.angle)+dy*Math.sin(tr.angle))*(tr.mirror?-1:1),y=-dx*Math.sin(tr.angle)+dy*Math.cos(tr.angle);b.ports[portDrag.key]=[clamp(x/tr.w+.5,0,1),clamp(y/tr.h+.5,0,1)];portDrag.moved=true;portEditor();draw()},{capture:true});
for(const event of ['pointerup','pointercancel'])canvas.addEventListener(event,e=>{if(!portDrag)return;e.stopImmediatePropagation();if(portDrag.moved){log('拖动连接点：'+portDrag.body.portNames[portDrag.key]);persist()}else undo.pop();portDrag=null;refresh()},{capture:true});
// Template wiring is explicit, independent of generic point order or availability.
function templatePoint(b,key,xy){b.ports[key]=clone(xy);b.portNames[key]='连接点 '+Object.keys(b.ports).length;b.portTypes[key]='any';return key}
function template(kind){const a=t=>state.assets.find(a=>a.type===t);state.parts=[];const b=addRaw(a('body').id,null);b.name=kind==='human'?'人形·躯干':kind==='beast'?'兽形·躯干':'蛇形·第1段';
 if(kind==='human'){b.width=190;b.heightScale=1.15;for(const key of ['neck','armL','armR','footL','footR'])templatePoint(b,key,CONFIG.ports[key]);addRaw(a('head').id,b,{mount:'neck'});for(const key of ['armL','armR'])addRaw(a('arm').id,b,{mount:key});for(const key of ['footL','footR'])addRaw(a('foot').id,b,{mount:key})}
 if(kind==='beast'){b.width=320;b.heightScale=.55;templatePoint(b,'neck',[.27,.32]);addRaw(a('head').id,b,{mount:'neck',width:125,rotation:-30});for(const[k,xy]of [['frontL',[.24,.76]],['frontR',[.35,.78]],['rearL',[.7,.77]],['rearR',[.81,.78]]]){templatePoint(b,k,xy);addRaw(a('foot').id,b,{mount:k,width:78,z:k.endsWith('R')?5:20})}}
 if(kind==='snake'){b.width=115;b.heightScale=.85;b.x=-240;templatePoint(b,'neck',[.24,.5]);let prev=b;for(let i=1;i<6;i++){templatePoint(prev,'next',[.77,.5]);const s=addRaw(a('body').id,prev,{mount:'next',name:'蛇形·第'+(i+1)+'段',width:115-i*8,heightScale:.85,anchor:[.24,.5],rotation:Math.sin(i)*8,mirror:false});prev=s}addRaw(a('head').id,b,{mount:'neck',width:110,rotation:-90,mirror:true});}
 selected=b.id;state.template=kind;
}
for(const kind of ['human','beast','snake'])$(kind+'Template').onclick=()=>{if(state.parts.length&&!confirm('套用模板会替换当前组合但保留素材库，可撤销。继续？'))return;change('套用标准模板：'+{human:'人形',beast:'兽形',snake:'蛇形'}[kind],()=>template(kind));fit()};
example=function(){state=initial();template('human');undo=[];redo=[];log('载入人形标准模板');refresh();persist();requestAnimationFrame(fit)};
$('reset').onclick=()=>{if(confirm('恢复人形示例并替换素材库，可撤销。继续？')){checkpoint();const history=undo.slice();example();undo=history;refresh()}};
const oldValidAsset=validAsset;
validAsset=function(a){oldValidAsset(a);if(typeof a.id!=='string'||!a.id)throw new Error('素材标识无效')};
validPart=function(p){if(!p||!TYPES[p.type]||typeof p.id!=='string'||!p.id||typeof p.name!=='string'||p.name.length>200)throw new Error('组件标识或类型无效');for(const[k,min,max]of [['width',10,1000],['heightScale',.2,4],['rotation',-180,180],['offsetX',-1000,1000],['offsetY',-1000,1000],['z',-100,100],['x',-2000,2000],['y',-2000,2000]])if(!Number.isFinite(p[k])||p[k]<min||p[k]>max)throw new Error('参数越界：'+k);if(!Array.isArray(p.anchor)||p.anchor.length!==2||!p.anchor.every(v=>Number.isFinite(v)&&v>=0&&v<=1)||typeof p.mirror!=='boolean'||typeof p.mount!=='string'||!(p.parentId===null||typeof p.parentId==='string'))throw new Error('连接参数无效');if(p.type==='body'){if(!p.ports||Object.keys(p.ports).length>40)throw new Error('连接点数量无效');for(const[k,v]of Object.entries(p.ports)){if(['__proto__','constructor','prototype'].includes(k)||!Array.isArray(v)||v.length!==2||!v.every(n=>Number.isFinite(n)&&n>=0&&n<=1)||typeof p.portNames?.[k]!=='string'||!['any',...Object.keys(TYPES)].includes(p.portTypes?.[k]))throw new Error('躯干连接点无效')}}};
validateProject=function(data){if(data.schema!=='monster-assembly'||![1,2].includes(data.version))throw new Error('方案版本不支持');const s=migrate(data);if(!Array.isArray(s.assets)||s.assets.length>200||!Array.isArray(s.parts)||s.parts.length>60||!Array.isArray(s.log))throw new Error('方案结构无效');s.assets.forEach(validAsset);s.parts.forEach(validPart);if(new Set(s.assets.map(a=>a.id)).size!==s.assets.length||new Set(s.parts.map(p=>p.id)).size!==s.parts.length)throw new Error('重复标识');for(const p of s.parts){if(!s.assets.some(a=>a.id===p.assetId&&a.type===p.type))throw new Error('缺失素材');let q=p;const visited=new Set();while(q.parentId){if(visited.has(q.id))throw new Error('循环连接');visited.add(q.id);const b=s.parts.find(b=>b.id===q.parentId);if(!b||b.type!=='body'||!b.ports[q.mount]||!['any',q.type].includes(b.portTypes[q.mount]))throw new Error('父躯干或接口无效');q=b;}}s.log=s.log.filter(e=>e&&typeof e.at==='string'&&typeof e.action==='string').slice(-500);return s};
$('savePart').onclick=()=>{const p=part();if(!p)return;const q=clone(p),tr=transform(p);q.parentId=null;q.mount='';q.x=tr.x;q.y=tr.y;log('导出独立组件：'+p.name);download({schema:'monster-component',version:2,asset:clone(asset(p.assetId)),part:q},filename(p.name)+'.component.json');refresh();persist()};
$('importPart').onclick=()=>pick('.json',async f=>{const data=JSON.parse(await f.text());if(data.schema!=='monster-component'||![1,2].includes(data.version))throw new Error('组件版本不支持');if(data.version===1){data.part.heightScale=1;data.part.parentId=null;if(data.part.type==='body'){data.part.portNames=Object.fromEntries(Object.keys(data.part.ports).map(k=>[k,PORTS[k]||k]));data.part.portTypes=Object.fromEntries(Object.keys(data.part.ports).map(k=>[k,portKind(k)]));}}validAsset(data.asset);validPart(data.part);if(data.asset.type!==data.part.type)throw new Error('素材类型不符');if(state.parts.length>=60)throw new Error('组件过多');change('导入独立组件：'+data.part.name,()=>{const a={...data.asset,id:uid()},p={...data.part,id:uid(),assetId:a.id,parentId:null,mount:''};state.assets.push(a);const b=body();if(b){p.parentId=b.id;p.mount=availablePort(b,p.type);p.offsetX=0;p.offsetY=0}state.parts.push(p);selected=p.id});fit()});
$('exportLog').onclick=()=>download({platformVersion:'0.2',entries:state.log},'拼接操作记录.json');
try{const saved=localStorage.getItem(CONFIG.storageKey);if(saved){state=validateProject(JSON.parse(saved));selected=bodies()[0]?.id;refresh();persist()}else example()}catch(e){try{const raw=localStorage.getItem(CONFIG.storageKey);if(raw)localStorage.setItem(CONFIG.storageKey+'-recovery',raw)}catch(backupError){}example();say('旧缓存无法转换；已尝试另存 recovery 备份后载入人形，请优先从导出的方案恢复。')}
requestAnimationFrame(()=>{canvasSize();fit()});
