'use strict';
// Independent workspace extension: file-backed gallery and front-to-back layer groups.
const workspacePanel=document.createElement('section');workspacePanel.className='workspace-panel';
workspacePanel.innerHTML='<h2>本地怪物作品库</h2><label>作品名称<input id="workName" maxlength="60" placeholder="给这只怪物命名"></label><div class="actions"><button id="saveWork">保存作品</button><button id="saveWorkAs">另存新作品</button><button id="chooseWorks">选择作品目录</button><button id="refreshWorks">刷新作品库</button></div><p id="galleryStatus" class="hint"></p><div id="gallery"></div><h2>层级组</h2><div class="actions"><input id="newLayerName" placeholder="新组名称，如 1 / 2 / 3" maxlength="40"><button id="addLayer">新建层级组</button></div><p class="hint">列表上方在前，下方在后。拖组调整前后；拖部件到组内或其它部件前排序。</p>';
$('parts').before(workspacePanel);
$('openWorkspace').onclick=()=>{$('workName').scrollIntoView({block:'center'});$('workName').focus()};
const layerField=document.createElement('label');layerField.textContent='部件所属层级组';const layerSelect=document.createElement('select');layerSelect.id='partLayer';layerField.append(layerSelect);$('z').parentElement.before(layerField);$('z').disabled=true;$('z').title='由层级组顺序决定，请拖动层级组或选择所属组';
function normalizeLayers(s){if(!s.layerGroups){const zs=[...new Set(s.parts.map(p=>p.z))].sort((a,b)=>a-b);s.layerGroups=(zs.length?zs:[1,2,3]).map((z,i)=>({id:uid(),name:String(i+1),legacyZ:z}));for(const p of s.parts)p.layerId=s.layerGroups.find(g=>g.legacyZ===p.z).id}
 if(!s.layerGroups.length)s.layerGroups=[{id:uid(),name:'1'}];for(const p of s.parts){if(!s.layerGroups.some(g=>g.id===p.layerId))p.layerId=(s.layerGroups.find(g=>g.legacyZ===p.z)||s.layerGroups.at(-1)).id;if(!Number.isFinite(p.layerOrder))p.layerOrder=Math.max(-1,...s.parts.filter(q=>q.layerId===p.layerId&&Number.isFinite(q.layerOrder)).map(q=>q.layerOrder))+1;p.z=s.layerGroups.findIndex(g=>g.id===p.layerId)+1}return s}
function validateLayers(s){if(s.layerGroups!==undefined){if(!Array.isArray(s.layerGroups)||s.layerGroups.length>40||new Set(s.layerGroups.map(g=>g?.id)).size!==s.layerGroups.length)throw new Error('层级组无效');for(const g of s.layerGroups)if(typeof g?.id!=='string'||!g.id||typeof g.name!=='string'||g.name.length>60)throw new Error('层级组名称无效');for(const p of s.parts)if(p.layerId!==undefined&&!s.layerGroups.some(g=>g.id===p.layerId)||p.layerOrder!==undefined&&(!Number.isFinite(p.layerOrder)||Math.abs(p.layerOrder)>10000))throw new Error('部件层级无效')}return normalizeLayers(s)}
const priorProjectValidation=validateProject;validateProject=function(data){return validateLayers(priorProjectValidation(data))};
sorted=function(){normalizeLayers(state);return [...state.parts].sort((a,b)=>state.layerGroups.findIndex(g=>g.id===a.layerId)-state.layerGroups.findIndex(g=>g.id===b.layerId)||a.layerOrder-b.layerOrder||state.parts.indexOf(a)-state.parts.indexOf(b))};
function createLayer(name){if(state.layerGroups.length>=40)throw new Error('最多 40 个层级组');const g={id:uid(),name:name.trim()||String(state.layerGroups.length+1)};state.layerGroups.push(g);return g}
function moveLayer(id,beforeId){const list=state.layerGroups,g=list.find(g=>g.id===id);if(!g||id===beforeId)return;state.layerGroups=list.filter(g=>g.id!==id);const i=beforeId?state.layerGroups.findIndex(g=>g.id===beforeId):state.layerGroups.length;state.layerGroups.splice(i<0?state.layerGroups.length:i,0,g)}
function moveLayerInFront(id,targetId){if(id===targetId)return;const rest=state.layerGroups.filter(g=>g.id!==id),i=rest.findIndex(g=>g.id===targetId);if(i>=0)moveLayer(id,rest[i+1]?.id||null)}
function movePartInFront(id,targetId){if(id===targetId)return;const target=state.parts.find(p=>p.id===targetId);if(!target)return;const rest=sorted().filter(p=>p.layerId===target.layerId&&p.id!==id),i=rest.findIndex(p=>p.id===targetId);moveToLayer(id,target.layerId,rest[i+1]?.id||null)}
function moveToLayer(id,groupId,beforePartId=null){const p=state.parts.find(p=>p.id===id);if(!p||!state.layerGroups.some(g=>g.id===groupId))throw new Error('部件或层级组不存在');const list=sorted().filter(q=>q.layerId===groupId&&q.id!==id);const i=beforePartId?list.findIndex(q=>q.id===beforePartId):list.length;list.splice(i<0?list.length:i,0,p);p.layerId=groupId;list.forEach((q,i)=>q.layerOrder=i);}
let layerDrag=null;
let layerPointer=null,ignoreLayerClick=false;
function beginLayerPointer(e,kind,id){if(e.button!==0||kind==='group'&&e.target.closest('button'))return;e.currentTarget.draggable=false;layerPointer={kind,id,x:e.clientX,y:e.clientY,moved:false}}
document.addEventListener('pointermove',e=>{if(!layerPointer)return;if(Math.hypot(e.clientX-layerPointer.x,e.clientY-layerPointer.y)>6){layerPointer.moved=true;e.preventDefault();document.body.style.cursor='grabbing'}});
document.addEventListener('pointerup',e=>{const d=layerPointer;layerPointer=null;document.body.style.cursor='';if(!d?.moved)return;ignoreLayerClick=true;setTimeout(()=>ignoreLayerClick=false,0);const target=document.elementFromPoint(e.clientX,e.clientY),row=target?.closest('[data-part-id]'),box=target?.closest('[data-layer-id]');if(!box)return;change('拖动层级排序',()=>{if(d.kind==='group')moveLayerInFront(d.id,box.dataset.layerId);else if(row)movePartInFront(d.id,row.dataset.partId);else moveToLayer(d.id,box.dataset.layerId)})});
document.addEventListener('pointercancel',()=>{layerPointer=null;document.body.style.cursor=''});
let renameTarget=null;
function openRename(kind,id){const item=(kind==='part'?state.parts:state.layerGroups).find(p=>p.id===id);if(!item)return;renameTarget={kind,id};$('renameTitle').textContent=kind==='part'?'重命名组合部件':'重命名层级组';$('renameValue').value=item.name;$('renameDialog').hidden=false;$('renameValue').focus?.()}
function renameCurrentPart(id){openRename('part',id)}
$('renameCancel').onclick=()=>{$('renameDialog').hidden=true;renameTarget=null};
$('renameConfirm').onclick=()=>{const t=renameTarget,name=$('renameValue').value.trim();if(!t||!name){say('名称不能为空');return}const item=(t.kind==='part'?state.parts:state.layerGroups).find(p=>p.id===t.id);if(!item)return;if(change('重命名：'+item.name,()=>{item.name=name.slice(0,60);if(t.kind==='part')selected=item.id})){ $('renameDialog').hidden=true;renameTarget=null}};
function allowDrop(el,fn){el.ondragover=e=>{e.preventDefault();e.dataTransfer.dropEffect='move';el.classList.add('drop-target')};el.ondragleave=()=>el.classList.remove('drop-target');el.ondrop=e=>{e.preventDefault();e.stopPropagation();el.classList.remove('drop-target');if(layerDrag){const d=layerDrag;layerDrag=null;change('拖动层级排序',()=>fn(d))}}}
const beforeWorkspaceLists=renderLists;
renderLists=function(){normalizeLayers(state);beforeWorkspaceLists();const list=$('parts');list.replaceChildren();for(const g of [...state.layerGroups].reverse()){const box=document.createElement('div');box.className='layer-group';box.dataset.layerId=g.id;const header=document.createElement('div');header.className='layer-header';header.draggable=true;const title=document.createElement('b');title.textContent='≡ 层级组 '+g.name;header.append(title);header.ondragstart=e=>{layerDrag={kind:'group',id:g.id};e.dataTransfer.setData('text/plain',g.id)};header.ondragend=()=>layerDrag=null;
 for(const [label,delta]of [['↑',1],['↓',-1]]){const btn=document.createElement('button');btn.textContent=label;btn.title=delta>0?'移到更前':'移到更后';btn.onclick=()=>change('调整层级组前后',()=>{const i=state.layerGroups.findIndex(q=>q.id===g.id),j=clamp(i+delta,0,state.layerGroups.length-1);[state.layerGroups[i],state.layerGroups[j]]=[state.layerGroups[j],state.layerGroups[i]]});header.append(btn)}
 const rename=document.createElement('button');rename.textContent='改名';rename.onclick=()=>openRename('group',g.id);header.append(rename);box.append(header);
 allowDrop(box,d=>{if(d.kind==='part')moveToLayer(d.id,g.id);else moveLayerInFront(d.id,g.id)});
 for(const p of sorted().reverse().filter(p=>p.layerId===g.id)){const wrap=document.createElement('div');wrap.className='part-row';const row=document.createElement('button');row.className='part'+(selected===p.id?' active':'');row.draggable=true;row.dataset.partId=p.id;row.textContent='⋮⋮ '+p.name;row.onclick=()=>{selected=p.id;editor();draw();for(const el of $('parts').querySelectorAll('.part'))el.classList.toggle('active',el.dataset.partId===selected)};row.ondblclick=()=>renameCurrentPart(p.id);row.ondragstart=e=>{e.stopPropagation();layerDrag={kind:'part',id:p.id};e.dataTransfer.setData('text/plain',p.id)};row.ondragend=()=>layerDrag=null;allowDrop(row,d=>{if(d.kind==='part'){const next=sorted().filter(q=>q.layerId===g.id),i=next.findIndex(q=>q.id===p.id);moveToLayer(d.id,g.id,next[i+1]?.id||null)}});const rename=document.createElement('button');rename.textContent='改名';rename.title='重命名部件：'+p.name;rename.onclick=()=>renameCurrentPart(p.id);wrap.append(row,rename);box.append(wrap)}if(!state.parts.some(p=>p.layerId===g.id)){const empty=document.createElement('p');empty.className='hint';empty.textContent='将部件拖到这里';box.append(empty)}list.append(box)}};
const beforeWorkspaceEditor=editor;editor=function(){beforeWorkspaceEditor();const p=part();if(p)options($('partLayer'),state.layerGroups.map(g=>[g.id,'层级组 '+g.name]),p.layerId)};
const beforePointerLists=renderLists;renderLists=function(){beforePointerLists();for(const box of $('parts').querySelectorAll('.layer-group')){const header=box.querySelector('.layer-header');header.draggable=false;header.onpointerdown=e=>beginLayerPointer(e,'group',box.dataset.layerId)}for(const row of $('parts').querySelectorAll('[data-part-id]')){row.draggable=false;row.onpointerdown=e=>beginLayerPointer(e,'part',row.dataset.partId);const click=row.onclick;row.onclick=e=>{if(!ignoreLayerClick)click(e)}}};
$('partLayer').onchange=()=>{const p=part();if(p)change('修改部件所属组',()=>moveToLayer(p.id,$('partLayer').value))};
$('addLayer').onclick=()=>{if(change('新建层级组',()=>createLayer($('newLayerName').value)))$('newLayerName').value=''};
let worksDirectory=null,galleryBackend=null,activeWorkId=state.workspaceId||null,galleryItems=[];
$('workName').value=state.workspaceName||'';
const beforeWorkspacePersist=persist;
persist=function(){state.workspaceId=activeWorkId;state.workspaceName=$('workName').value;beforeWorkspacePersist();$('storageStatus').textContent+=' 点击“保存作品”才会写入可同步的本地文件。'};
const WORK_LIMIT=64*1024*1024;
function validateWork(record){if(record?.schema!=='monster-work'||record.version!==1||!/^[a-zA-Z0-9-]{1,80}$/.test(record.id)||typeof record.name!=='string'||record.name.length>100||typeof record.preview!=='string'||!/^data:image\/png;base64,/.test(record.preview))throw new Error('作品文件无效');record.project=validateProject(record.project);return record}
async function previewImage(){await Promise.all(state.parts.map(p=>{const im=imageFor(asset(p.assetId).src);return im.complete?Promise.resolve():new Promise(resolve=>{im.addEventListener('load',resolve,{once:true});im.addEventListener('error',resolve,{once:true})})}));const c=document.createElement('canvas');c.width=320;c.height=320;const cc=c.getContext('2d'),corners=state.parts.flatMap(p=>[point(transform(p),0,0),point(transform(p),0,1),point(transform(p),1,0),point(transform(p),1,1)]);cc.translate(160,160);if(corners.length){const xs=corners.map(p=>p.x),ys=corners.map(p=>p.y),x1=Math.min(...xs),x2=Math.max(...xs),y1=Math.min(...ys),y2=Math.max(...ys),s=280/Math.max(x2-x1,y2-y1,1);cc.scale(s,s);cc.translate(-(x1+x2)/2,-(y1+y2)/2)}paint(cc,false);return c.toDataURL('image/png')}
function galleryMessage(s){$('galleryStatus').textContent=s}
async function api(path,options={}){const response=await fetch(path,options);if(!response.ok)throw new Error((await response.json()).error||'本地服务未响应');return response.json()}
async function listWorks(){if(worksDirectory){const list=[];let skipped=0;for await(const [name,handle]of worksDirectory.entries()){if(handle.kind!=='file'||!name.endsWith('.work.json'))continue;try{const f=await handle.getFile();if(f.size>WORK_LIMIT)throw new Error('文件过大');const r=validateWork(JSON.parse(await f.text()));list.push({id:r.id,name:r.name,preview:r.preview,updatedAt:r.updatedAt,fileName:name})}catch(e){skipped++}}if(skipped)galleryMessage('已跳过 '+skipped+' 个无效作品文件。');return list.sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''))}return api('/api/works')}
async function readWork(id){if(worksDirectory){const item=galleryItems.find(w=>w.id===id);if(!item)throw new Error('作品不存在');return validateWork(JSON.parse(await (await (await worksDirectory.getFileHandle(item.fileName)).getFile()).text()))}return validateWork(await api('/api/works/'+encodeURIComponent(id)))}
async function writeWork(record){const text=JSON.stringify(record,null,2);if(new Blob([text]).size>WORK_LIMIT)throw new Error('作品超过 64 MB，请压缩素材');if(worksDirectory){const item=galleryItems.find(w=>w.id===record.id),name=item?.fileName||record.id+'.work.json';if(item){const h=await worksDirectory.getFileHandle(name),old=await h.getFile(),history=await worksDirectory.getDirectoryHandle('历史备份',{create:true}),backup=await history.getFileHandle(record.id+'-'+Date.now()+'.work.json',{create:true}),writer=await backup.createWritable();await writer.write(await old.text());await writer.close()}const handle=await worksDirectory.getFileHandle(name,{create:true}),writer=await handle.createWritable();await writer.write(text);await writer.close();return}await api('/api/works/'+encodeURIComponent(record.id),{method:'PUT',headers:{'Content-Type':'application/json'},body:text})}
async function loadWork(id){try{const r=await readWork(id);if(!confirm('载入作品会替换当前编辑内容，可撤销。继续？'))return;if(change('载入本地作品：'+r.name,()=>{state=r.project;selected=null})){activeWorkId=r.id;$('workName').value=r.name;persist();fit();galleryMessage('正在编辑：'+r.name+'；修改后点击保存作品写回磁盘。')}}catch(e){galleryMessage(e.message)}}
function renderGallery(){const root=$('gallery');root.replaceChildren();for(const w of galleryItems){const card=document.createElement('div');card.className='work-card';const img=document.createElement('img');img.src=w.preview;img.alt=w.name;const btn=document.createElement('button');btn.textContent=w.name+' · 载入编辑';btn.onclick=()=>loadWork(w.id);card.append(img,btn);root.append(card)}if(!galleryItems.length){const text=document.createElement('p');text.className='hint';text.textContent='尚无作品。保存后可在此查看与继续编辑。';root.append(text)}}
async function refreshGallery(){try{galleryItems=await listWorks();galleryBackend=worksDirectory?'directory':'server';if(activeWorkId&&!galleryItems.some(w=>w.id===activeWorkId))activeWorkId=null;renderGallery();galleryMessage('作品库已连接 · '+galleryItems.length+' 件 · '+(worksDirectory?'所选本地目录':'项目内作品库'))}catch(e){galleryBackend=null;galleryMessage('请启动本地服务，或点击“选择作品目录”授权写入；浏览器缓存不会进入 Git。')}}
async function saveWork(asNew=false){try{if(!worksDirectory&&!galleryBackend)throw new Error('先选择作品目录，或从本地服务打开平台。');const name=$('workName').value.trim();if(!name)throw new Error('请先填写作品名称');const project=clone(normalizeLayers(state)),record={schema:'monster-work',version:1,id:asNew||!activeWorkId?uid():activeWorkId,name,updatedAt:new Date().toISOString(),preview:await previewImage(),project};await writeWork(record);activeWorkId=record.id;await refreshGallery();galleryMessage('已写入本地文件：'+name+'；可通过 Git 同步。');log('保存本地作品：'+name);refresh();persist()}catch(e){galleryMessage('保存未完成：'+e.message)}}
$('saveWork').onclick=()=>saveWork(false);$('saveWorkAs').onclick=()=>saveWork(true);$('refreshWorks').onclick=refreshGallery;
$('chooseWorks').onclick=async()=>{try{if(!window.showDirectoryPicker)throw new Error('此浏览器不支持目录授权，请使用本地服务版。');worksDirectory=await window.showDirectoryPicker({mode:'readwrite'});galleryBackend='directory';activeWorkId=null;await refreshGallery()}catch(e){galleryMessage('目录未连接：'+e.message)}};
normalizeLayers(state);refresh();persist();
if(location.protocol==='http:'||location.protocol==='https:'){api('/api/works').then(list=>{galleryBackend='server';galleryItems=list;renderGallery();galleryMessage('已连接项目内作品库 · '+list.length+' 件')}).catch(()=>galleryMessage('选择作品目录，或运行“启动平台.cmd”使用本地文件作品库。'))}else galleryMessage('本地 HTML 模式：点击“选择作品目录”，建议选择本平台的作品库文件夹。');
